# Generated by Django 5.1.7 on 2025-03-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_input', models.CharField(max_length=1000)),
                ('response', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
