# Generated by Django 5.1.7 on 2025-03-13 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(default=0.0016666666666666666, on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='app.user'),
            preserve_default=False,
        ),
    ]
